version: "3"

networks:
  backend:
    driver: "host"

services:
  scaffold:
    container_name: ${SERVICE_NAME}
    tty: true
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile
    working_dir: /${SERVICE_NAME}
    volumes:
      - .:/${SERVICE_NAME}
    ports:
      - ${SCAFFOLD_PORT}:8080
    env_file: env
    links:
      - "scaffold_db:db"
    depends_on:
      - scaffold_db

  scaffold_db:
    container_name: scaffold_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d ${SERVICE_NAME}"]
      interval: 15s
      timeout: 1m
      retries: 5
      start_period: 30s
    image: postgres
    restart: always
    env_file: env
    ports:
      - ${SCAFFOLD_DB_PORT}:5432