version: "3"
services:
  scaffold_test:
    container_name: scaffold_test
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:1001/api/v1/scaffold/"]
      interval: 10s
      timeout: 1m
      retries: 3
      start_period: 30s
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile_Newman
    env_file: .env
    tty: true
    # depends_on:
    #   scaffold_db:
    #     condition: service_healthy
    network_mode: "host"