// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/google/wire"
	"github.com/sirupsen/logrus"
	"gorm.io/gorm"
	"ms-scaffold/api/controller"
	"ms-scaffold/api/helper"
	"ms-scaffold/api/repository"
	"ms-scaffold/api/service"
)

// Injectors from injector.go:

func InitScaffold(db *gorm.DB) controller.ScaffoldController {
	scaffoldRepository := repository.NewScaffoldRepository(db)
	scaffoldService := service.NewScaffoldService(scaffoldRepository)
	logger := logrus.New()
	log := helper.NewLog(logger)
	scaffoldController := controller.NewScaffoldController(scaffoldService, log)
	return scaffoldController
}

// injector.go:

var scaffoldSet = wire.NewSet(logrus.New, helper.NewLog, controller.NewScaffoldController, repository.NewScaffoldRepository, service.NewScaffoldService)
