// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/google/wire"
	"gorm.io/gorm"
	"ms-scaffold/api/controller"
	"ms-scaffold/api/repository"
	"ms-scaffold/api/service"
)

// Injectors from injector.go:

func InitScaffold(db *gorm.DB) controller.ScaffoldController {
	scaffoldRepository := repository.NewScaffoldRepository(db)
	scaffoldService := service.NewScaffoldService(scaffoldRepository)
	scaffoldController := controller.NewScaffoldController(scaffoldService)
	return scaffoldController
}

// injector.go:

var scaffoldSet = wire.NewSet(repository.NewScaffoldRepository, service.NewScaffoldService, controller.NewScaffoldController)
