name: REST API Deployment and Test


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Start Container
      run: make orphans

    - name: Start API Server
      run: docker compose -f "docker-compose.yml" up --build -d

    - name: Sleep
      run: sleep 15s

    - name: Show docker process
      run: docker ps

    - name: Show netstat
      run: netstat -tulpn

    # - name: Check if connection running
    #   run: curl http://localhost:1001/api/v1/scaffold/

    # - name: API Testing
    #   run: docker compose -f "docker-compose.yml" up --build -d scaffold_test

    - name: Install Newman
      run: npm install -g newman
      
    - name: Run integrated tests using Postaman Runner by Newman
      run: newman run test/Scaffold.postman_collection.json --bail --verbose


    # - name: Newman
    #   uses: matt-ball/newman-action@master
    #   with:
    #     collection: test/Scaffold.postman_collection.json
