name: REST API Deployment and Test


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Start Container
      run: make orphans

    - name: Start Database
      run: docker compose -f "docker-compose.yml" up --build -d scaffold_db

    - name: Start API Server
      run: docker compose -f "docker-compose.yml" up --build -d scaffold

    - name: Sleep
      run: sleep 15s

    - name: Show docker process
      run: docker ps

    - name: Show netstat
      run: netstat -tulpn

    - name: Check if connection running
      run: curl -s -i http://localhost:1001/api/v1/scaffold/ | head -1
      # run: curl http://localhost:1001/api/v1/scaffold/

    - name: API Testing
      run: docker compose -f "docker-compose.yml" up --build -d scaffold_test

    # - name: Newman
    #   uses: matt-ball/newman-action@master
    #   with:
    #     collection: test/Scaffold.postman_collection.json
